version: '3.8'
services:
  psql-db:
    build: ./src-psql
    ports:
      - "5432:5432"
    expose:
      - 5432
  go-backend:
    build: ./src
    depends_on:
      - psql-db
    environment:
      POSTGRES_HOST: psql-db
      POSTGRES_PORT: 5432
    ports:
      - "8080:8080"
  react-frontend:
    build: ./src-ui
    depends_on:
      - go-backend
    ports:
      - "3000:3000"