version: '3.8'
services:
  psql-db:
    image: beebeeoii/do-gether-psql-db:latest
    ports:
      - "5432:5432"
    expose:
      - 5432
  backend:
    image: beebeeoii/do-gether-backend:latest
    depends_on:
      - psql-db
    environment:
      POSTGRES_HOST: psql-db
      POSTGRES_PORT: 5432
    ports:
      - "8080:8080"
  frontend:
    image: beebeeoii/do-gether-frontend:latest
    depends_on:
      - backend
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
    ports:
      - "3000:3000"